src/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^ru/$', views.CartDetailRu, name='CartDetailRu'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^add_discount/(?P<phone_number>\d+)/$', views.CartAddDiscount, name='CartAddDiscount'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include, url

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('boss/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    re_path(r'', include(('pasta_family.urls', 'pasta_family'), namespace='pasta_family')),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('orders.urls', 'orders'), namespace='orders')),
    path('novaposhta/', include('novaposhta.urls')),
    url(r'', include(('loyalty_program.urls', 'loyalty_program'), namespace='loyalty_program')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/novaposhta/urls.py
from django.conf.urls import url

from novaposhta import views


app_name = 'novaposhta'


urlpatterns = [

    url('autocomplete', views.autocomplete, name='autocomplete'),

    url('refresh', views.refresh, name='refresh')

]

src/pasta_family/urls.py
from django.urls import re_path
from django.conf.urls import url
import django.views.defaults
from . import views

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^about/$', views.AboutView.as_view(), name='about'),
    re_path(r'^ofert/$', views.OfertView.as_view(), name='ofert'),
    re_path(r'^ru/ofert/$', views.OfertRuView.as_view(), name='ofert ru'),
    re_path(r'^ru/return/$', views.ReturnRuView.as_view(), name='return ru'),
    re_path(r'^return/$', views.ReturnView.as_view(), name='return'),
    re_path(r'^for_sportmens/$', views.SportView.as_view(), name='sport'),
    re_path(r'^contacts/$', views.ContactView.as_view(), name='contact'),
    re_path(r'^delivery/$', views.DeliveryView.as_view(), name='delivery'),
    url(r'^cooperation/$', views.cooperation_new, name='cooperation'),
    re_path(r'^product_group/$', views.product_group, name='product_group'),
    re_path(r"^product_group/(?P<productgroup_slug>.+[\w-]+[']*)/(?P<product_slug>.+[\w-]+[']*)/$",
            views.ProductView.as_view(), name='product'),
    url(r'^review/$', views.review_new, name='review'),
    re_path(r'^form_send/$', views.FormSendView.as_view(), name='form_send'),
    re_path(r"^product_group/(?P<productgroup_slug>.[\w-]+[']*)/$", views.ProductsView.as_view(), name='products'),

    re_path(r'^ru/$', views.IndexRuView.as_view(), name='index'),
    re_path(r'^ru/about/$', views.AboutRuView.as_view(), name='about'),
    re_path(r'^ru/for_sportmens/$', views.SportRuView.as_view(), name='sport'),
    re_path(r'^ru/contacts/$', views.ContactRuView.as_view(), name='contact'),
    re_path(r'^ru/delivery/$', views.DeliveryRuView.as_view(), name='delivery'),
    url(r'^ru/cooperation/$', views.cooperation_new_ru, name='cooperation'),
    re_path(r'ru/product_group/$', views.product_group_ru, name='product_group'),
    re_path(r"^ru/product_group/(?P<productgroup_slug>.+[\w-]+[']*)/(?P<product_slug>.+[\w-]+[']*)/$",
            views.ProductRuView.as_view(), name='product'),
    url(r'^ru/review/$', views.review_new_ru, name='review'),
    re_path(r'^ru/form_send/$', views.FormSendRuView.as_view(), name='form_send'),
    re_path(r"^ru/product_group/(?P<productgroup_slug>[\w-]+[']*)/$", views.ProductsRuView.as_view(), name='products'),
    url(r'^404/$', django.views.defaults.page_not_found, ),
    url(r'^order_check/$', views.order_check, name='order_check'),
    url(r'^order_details/$', views.order_detail, name='order_detail'),
    url(r'^ru/order_check/$', views.order_check_ru, name='order_check'),
    url(r'^ru/order_details/$', views.order_detail_ru, name='order_detail'),
    url(r"^ajax/refresh_cart/$", views.refresh_cart, name='refresh_cart'),
]

src/pasta_family/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.utils.translation import gettext as _


class User(AbstractUser):
    username = models.CharField(
        max_length=64,
        unique=True,
        blank=True,
        null=True,
        verbose_name=_('Username'),
    )

    first_name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('First Name'),
    )

    last_name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Last Name'),
    )

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17)  # validators should be a list

    email = models.EmailField(max_length=70,)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Product(models.Model):
    availability = models.BooleanField(verbose_name='Availability', default=False)
    hidden = models.BooleanField(verbose_name='Hidden', default=False)
    name_ru = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Product In Russian'),
    )

    name_en = models.CharField(
        max_length=64,
        blank=True,
        verbose_name=_('Product In English'),
    )

    name_ua = models.CharField(
        max_length=64,
        verbose_name=_('Product In Ukraine'),
    )

    slug = models.CharField(
        max_length=150,
        unique=True,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    description_ru = models.CharField(
        max_length=1000,
        verbose_name=_('Description In Russian'),
        blank=True,
    )

    description_en = models.CharField(
        max_length=1000,
        blank=True,
        verbose_name=_('Description In English')
    )

    description_ua = models.CharField(
        max_length=1000,
        verbose_name=_('Description In Ukraine'),
        blank=True,
    )

    product_group = models.ForeignKey(
        to='ProductGroup',
        related_name='products',
        on_delete=models.PROTECT,
        verbose_name=_('Group'),
        blank=False
    )

    product_type = models.ForeignKey(
        to='ProductType',
        related_name='products',
        on_delete=models.PROTECT,
        verbose_name=_('Type'),
        blank=False
    )

    old_price = models.IntegerField(verbose_name=_('Old Price'), blank=True, null=True)

    price = models.IntegerField(verbose_name=_('Price'))

    weight = models.ForeignKey(
        to='ProductWeight',
        related_name='products',
        on_delete=models.PROTECT,
        verbose_name=_('Weight'),
        blank=False
    )

    ingredients_ru = models.TextField(
        max_length=2048,
        verbose_name=_('Ingredients In Russian'),
        blank=True,
    )

    ingredients_ua = models.TextField(
        max_length=2048,
        verbose_name=_('Ingredients In Ukraine'),
        blank=True,
    )

    ingredients_en = models.TextField(
        max_length=2048,
        verbose_name=_('Ingredients In English'),
        blank=True,
    )

    main_product = models.BooleanField(default=False, verbose_name=_('Main'))

    image_main = models.ImageField(verbose_name=_('Image Main'))

    image_2 = models.ImageField(verbose_name=_('Image 2'))

    image_3 = models.ImageField(verbose_name=_('Image 3'), blank=True, null=True)

    def __str__(self):
        return self.name_ru


class ProductGroup(models.Model):
    name_ru = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Group In Russian'),
    )

    name_en = models.CharField(
        max_length=64,
        blank=True,
        verbose_name=_('Group In English'),
    )

    name_ua = models.CharField(
        max_length=64,
        blank=True,
        verbose_name=_('Group In Ukraine'),
    )

    slug = models.CharField(
        max_length=150,
        unique=True,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    image = models.ImageField(verbose_name=_('Image'))

    image_ru = models.ImageField(verbose_name=_('Image Ru'), blank=True, null=True)

    def __str__(self):
        return self.name_ru


class Cooperation(models.Model):
    created = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Created at'),
        null=True
    )

    name = models.CharField(
        max_length=64,
        verbose_name=_('Name'),
    )

    email = models.EmailField(
        max_length=70,
    )

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'")

    phone = models.CharField(validators=[phone_regex], max_length=17)

    type = models.ForeignKey(
        to='CooperationType',
        on_delete=models.PROTECT,
        verbose_name=_('Type'),
        blank=False,
    )

    form = models.ForeignKey(
        to='CooperationForm',
        on_delete=models.PROTECT,
        verbose_name=_('Form'),
        blank=False,
    )

    def __str__(self):
        return self.name


class CooperationType(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name=_('Name'),
    )

    def __str__(self):
        return self.name


class CooperationForm(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name=_('Name'),
    )

    def __str__(self):
        return self.name


class ReviewNew(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name=_('Name'),
    )

    description = models.CharField(
        max_length=200,
        verbose_name=_('Description')
    )

    RATING_NUMBER = (
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, "4"),
        (5, "5")
    )

    rating = models.IntegerField(choices=RATING_NUMBER, default='5')

    check_by_moderator = models.BooleanField(default=False)

    product = models.ForeignKey(
        to='Product',
        on_delete=models.CASCADE,
        verbose_name=_('product'),
        blank=False,
    )

    def save(self, *args, **kwargs):
        if self.check_by_moderator == True:
            review = Review.objects.create(name=self.name,
                                           description=self.description,
                                           rating=self.rating,
                                           product=self.product,
                                           )
            review.save()
            self.delete()
        else:
            super(ReviewNew, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Review(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name=_('Name'),
    )

    description = models.CharField(
        max_length=200,
        verbose_name=_('Description')
    )

    RATING_NUMBER = (
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, "4"),
        (5, "5")
    )

    rating = models.IntegerField(choices=RATING_NUMBER, default='5')

    product = models.ForeignKey(
        to='Product',
        on_delete=models.CASCADE,
        verbose_name=_('product'),
        blank=False,
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created at'),
        null=True
    )
    def __str__(self):
        return self.name


class ProductType(models.Model):
    hidden = models.BooleanField(verbose_name='Hidden', default=False)
    name_ru = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Name In Russian'),
    )

    name_en = models.CharField(
        max_length=64,
        blank=True,
        verbose_name=_('Name In English'),
    )

    name_ua = models.CharField(
        max_length=64,
        blank=True,
        verbose_name=_('Name In Ukraine'),
    )

    slug = models.CharField(
        max_length=150,
        unique=True,
        blank=True,

        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    group = models.ForeignKey(
        to='ProductGroup',
        on_delete=models.PROTECT,
        verbose_name=_('group'),
        blank=False,
    )

    def __str__(self):
        return self.name_ru


class ProductWeight(models.Model):
    name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Name'),
    )

    weight = models.IntegerField(verbose_name=_('Weight'))

    def __str__(self):
        return self.name


class Price(models.Model):
    name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name=_('Name'),
    )

    price = models.FileField(
        verbose_name=_('File')
    )

    first_price = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class MainPhoto(models.Model):
    name = models.CharField(verbose_name="Name", max_length=50)
    photo = models.ImageField(verbose_name="Photo")
    active = models.BooleanField(verbose_name="Active", default=False)
    ru_version = models.BooleanField(verbose_name="Ru version", default=False)

    def __str__(self):
        return self.name


class AboutCompanyPhoto(models.Model):
    name = models.CharField(verbose_name="Name", max_length=50)
    photo_one = models.ImageField(verbose_name="Photo One", blank=True, null=True)
    photo_two = models.ImageField(verbose_name="Photo One", blank=True, null=True)
    active = models.BooleanField(verbose_name="Active", default=False)

    def __str__(self):
        return self.name

src/pasta_family/forms.py
from django import forms
from pasta_family import models
from pasta_family.models import CooperationForm, CooperationType, Product
import re
from transliterate import translit
from transliterate.exceptions import LanguageDetectionError
from django.forms.widgets import TextInput


def transliterate(text):
    pieces = str(re.sub('[\W]+', ' ', text)).lower().split(' ')
    result = []

    for piece in pieces:
        try:
            result.append(translit(piece, reversed=True))
        except LanguageDetectionError:
            result.append(piece)
    return '-'.join([r for r in result if r])


class UserForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = '__all__'


class ProductForm(forms.ModelForm):
    def clean_slug(self):
        return transliterate(self.cleaned_data['name_ru'])

    class Meta:
        model = models.Product
        fields = '__all__'


class ProductGroupForm(forms.ModelForm):
    def clean_slug(self):
        return transliterate(self.cleaned_data['name_ru'])

    class Meta:
        model = models.ProductGroup
        fields = '__all__'


class ProductWeightForm(forms.ModelForm):
    class Meta:
        model = models.ProductWeight
        fields = '__all__'


class CooperationTypeForm(forms.ModelForm):
    class Meta:
        model = models.CooperationType
        fields = '__all__'


class CooperationFormForm(forms.ModelForm):
    class Meta:
        model = models.CooperationForm
        fields = '__all__'


class CooperationForm(forms.ModelForm):
    name = forms.CharField(widget=TextInput(attrs={'placeholder': 'ПІБ/Назва компанії'}), min_length=4, max_length=150)
    email = forms.EmailField(widget=TextInput(attrs={'placeholder': 'Email'}), max_length=254)
    phone = forms.CharField(widget=TextInput(attrs={'placeholder': 'Номер телефона'}), min_length=6)
    type = forms.ModelChoiceField(queryset=CooperationType.objects.all(), empty_label='Тип')
    form = forms.ModelChoiceField(queryset=CooperationForm.objects.all(), empty_label='Организационно-правовая форма')

    class Meta:
        model = models.Cooperation
        fields = '__all__'


class ProductTypeForm(forms.ModelForm):
    def clean_slug(self):
        return transliterate(self.cleaned_data['name_ru'])

    class Meta:
        model = models.ProductType
        fields = '__all__'


class ReviewForm(forms.ModelForm):
    name = forms.CharField(min_length=4, max_length=150)
    product = forms.ModelChoiceField(queryset=Product.objects.all(), empty_label='Select the product')

    class Meta:
        model = models.Review
        fields = '__all__'


class ReviewNewForm(forms.ModelForm):
    name = forms.CharField(min_length=4, max_length=150)
    product = forms.ModelChoiceField(queryset=Product.objects.all(), empty_label='Select the product')

    class Meta:
        model = models.ReviewNew
        fields = '__all__'


class PriceForm(forms.ModelForm):
    class Meta:
        model = models.Price
        fields = '__all__'


class MainPhotoForm(forms.ModelForm):
    class Meta:
        model = models.MainPhoto
        fields = '__all__'


class AboutCompanyPhotoForm(forms.ModelForm):
    class Meta:
        model = models.MainPhoto
        fields = '__all__'

src/pasta_family/templates/pasta_family/cooperation.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ _('Співпраця') }}{% endblock %}
{% block content %}
<div id="content" class="container-fluid">
    <div class="article-wrapper row">
        <article>
            <div class="entry-content">
                <div class="cooperation_all col-sm-12">
                    <h1 style="text-align: center;"><font color="#df853a">Співпраця</font></h1>
                    <div class="line"></div>
                    <p style="text-align: center;"> PastaFamily керується філософією натуральної та здорової їжі.  Тому ми хочемо надати споживачеві корисну, натуральну і звичайно ж смачну продукцію.  Ми відкриті для співпраці як для підприємств роздрібної торгівлі, так і для оптової.<br> Ми надаємо якісну, свіжу продукцію у фірмовій упаковці в найкоротші терміни.</p>
                </div>
                <div class="col-sm-12 cooperation_all gray1">
                    <h2 style="text-align: center;">Наша співпраця можливе в двох векторах, кожен з яких включає в себе різні типи:</h2>
                </div>
                <div class="col-sm-12 cooperation_all gray">
                    <div class="first_adv col-sm-6">
                        <h3>Оптовий продаж у фірмовій упаковці 500, 450, 270 І 50 грам, для:</h3>
                        <ul>
                            <li>роздрібних торгових точок;</li>
                            <li>еколавок;</li>
                            <li>магазинів спортивного харчування;</li>
                            <li>ексклюзивних магазинів;</li>
                            <li>інтернет-магазинів, та ін;</li>
                            {% for i in price1 %}
                            <form method="get" action="{{ i.price.url }}">
                                <button type="submit">Скачати Прайс</button>
                            </form>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="second_adv col-sm-6">
                        <h3>Оптовий продаж у фасованні 3 кілограми, в якій наша паста поставляється як сировина для:</h3>
                        <ul>
                            <li>підприємств, які займаються виготовленням кондитерських виробів;</li>
                            <li>для кафе, ресторанів та інших закладів в сфері харчування як інгредієнт в різних стравах;</li>
                            <li>виробництв, магазинів, що спеціалізуються на виготовленні напівфабрикатів;</li>
                            {% for i in price2 %}
                            <form method="get" action="{{ i.price.url }}">
                                <button type="submit">Скачати Прайс</button>
                            </form>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="cooperation_all  advanced col-sm-12">
                    <div class="coop_title">ЧОМУ З НАМИ ВИГІДНО?</div>
                    <div class="col-sm-4">
                        <span class="title_line">ОПТОВИКАМ</span>
                    </div>
                    <div class="col-sm-4 col-sm-offset-4">
                        <span class="title_line">ДИСТРИБ'ЮТОРАМ</span>
                    </div>
                    <div class="col-sm-4">
                        <img src="{% static '/assets/img/1.png' %}">
                        <span class="first_line">ВИСОКА МАРЖИНАЛЬНІСТЬ</span>
                        <span class="second_line">від 18%</span>
                    </div>
                    <div class="col-sm-4">
                        <img src="{% static '/assets/img/4.jpg' %}">
                        <span class="first_line">ДОМОВИМОСЬ!</span>
                        <span class="second_line">Гнучка політика співпраці</span>
                    </div>
                    <div class="col-sm-4">
                        <img src="{% static '/assets/img/5.png' %}">
                        <span class="first_line">МІНІМАЛЬНЕ ЗАМОВЛЕННЯ</span>
                        <span class="second_line">всього від 5 тис. грн.</span>
                    </div>
                    <div class="col-sm-4">
                        <img src="{% static '/assets/img/2.png' %}">
                        <span class="first_line">НЕВЕЛИКІ ОБСЯГИ</span>
                        <span class="second_line">всього від 30 одиниць</span>
                    </div>
                    <div class="col-sm-4">
                        <img src="{% static '/assets/img/3.png' %}">
                        <span class="first_line">БЕЗКОШТОВНА ДОСТАВКА</span>
                        <span class="second_line">по місту Київ і передмісті</span>
                    </div>
                    <div class="col-sm-4">
                        <img src="{% static '/assets/img/6.png' %}">
                        <span class="first_line">ЗНИЖКИ + БОНУСИ</span>
                        <span class="second_line">знижки до 30% + грошові бонуси;</span>
                    </div>
                </div>
                <div class="cooperation_all col-sm-12">
                    <div class="coop_title cooperation_all gray"><img src="{% static '/assets/img/business.png' %}" alt="">ЯК ПОЧАТИ СПІВПРАЦЮ?</div>
                    <p>Якщо Ви ознайомилися з нашим прайсом і у Вас є зацікавленість у взаємовигідній співпраці, то далі потрібно заповнити більш детальну форму, після обробки якої, ми із задоволенням зв'яжемося з Вами якомога швидше.</p>
                    <div class="col-sm-12 cooperation_all">
                        <div class="wpb_column vc_column_container vc_col-sm-3">
                            <div class="vc_column-inner ">
                                <div class="wpb_wrapper"></div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-sm-offset-3">
                            <form class="login-page-form" method="POST">
                                {% csrf_token %}
                                <div class="input-group field-cooperation-name required">
                                    <input type="text" name="name" placeholder="Ім'я/Назва компанії" maxlength="150" minlength="4" required="" id="id_name">
                                </div>
                                <div class="input-group field-cooperation-name required">
                                    <input type="text" name="email" placeholder="Email" maxlength="254" required="" id="id_email">
                                </div>
                                <div class="input-group field-cooperation-name required">
                                    <input type="text" name="phone" placeholder="Номер телефону" minlength="6" required="" id="id_phone">
                                </div>
                                <div class="input-group field-cooperation-name required">
                                    <select name="type" required="" id="id_type">
                                        <option value="" selected="">Тип</option>
                                        {% for type in types %}
                                        <option value="{{ type.id }}">{{ type.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <br/>
                                <div class="input-group field-cooperation-name required">
                                    <select name="form" required="" id="id_form">
                                        <option value="" selected="">Організаційно-правова форма</option>
                                        {% for form in forms %}
                                        <option value="{{ form.id }}">{{ form.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <button class="save btn btn-default" type="submit" name="submit">Відправити</button>
                            </form>
                        </div>


                    </div>
                </div>
            </div>
        </article>
    </div>
</div>
{% endblock %}

src/pasta_family/templates/pasta_family/order_check.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ _('Статус замовлення') }}{% endblock %}
{% block content %}
<div id="content" class="container-fluid">
    <div class="row">
        <div class="wpb_wrapper">
            <br>
            <h1>Перевірити статус замовлення</h1>
            <div class="line"></div>
        </div>
        <div class="container p-t-35 p-b-80">
            <div class="container-fluid">
                <div class="wpb_wrapper">
                    <div class="row">
                        <form action="." method="post">
                            <div class="form-group col-sm-6 col-sm-offset-3" >
                                <label class="control-label requiredField">
                                    <font color="#555555">Номер замовлення:</font>
                                    <span class="asteriskField">
                                        <font color="#555555">*</font>
                                    </span>
                                </label>
                                <div class="input-group">
                                <input class="form-control" name="id" type="integerfield" maxlength="50" required="" id="id_name"/>
                                </div>
                            </div>
                            {% csrf_token %}
                            <div class="form-group col-sm-6 col-sm-offset-3">
                                <div>
                                    <input name="_honey" style="display:none" type="text"/>
                                    <button class="btn btn-warning " name="submit" type="submit">
                                        Відправити!
                                    </button>
                                    <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/pasta_family/templates/pasta_family/order_check_ru.html
{% extends 'core/base_ru.html' %}
{% load static %}

{% block title %}{{ _('Статус заказа') }}{% endblock %}
{% block content %}
<div id="content" class="container-fluid">
    <div class="row">
        <div class="wpb_wrapper">
            <br>
            <h1>Проверить статус заказа</h1>
            <div class="line"></div>
        </div>
        <div class="container p-t-35 p-b-80">
            <div class="container-fluid">
                <div class="wpb_wrapper">
                    <div class="row">
                        <form action="." method="post">
                            <div class="form-group col-sm-6 col-sm-offset-3" >
                                <label class="control-label requiredField">
                                    <font color="#555555">Номер заказа:</font>
                                    <span class="asteriskField">
                                        <font color="#555555">*</font>
                                    </span>
                                </label>
                                <div class="input-group">
                                <input class="form-control" name="id" type="integerfield" maxlength="50" required="" id="id_name"/>
                                </div>
                            </div>
                            {% csrf_token %}
                            <div class="form-group col-sm-6 col-sm-offset-3">
                                <div>
                                    <input name="_honey" style="display:none" type="text"/>
                                    <button class="btn btn-warning " name="submit" type="submit">
                                        Отправить!
                                    </button>
                                    <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/pasta_family/templates/pasta_family/product_group.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ _('Товари') }}{% endblock %}
{% block content %}
<div id="content" class="container-fluid">
    <div class="row">
        <article>
			<br>
			<h1><font color="#f97e05">Товари</font></h1>
			<div class="line"></div>
			<div class="product-category-wall wall-row">
				<div id="wrapper" class="wide-wrap">
					<div class="content-container no-padding">
						<div class="col-md-12 main-wrap" style="padding: 15px">
							<div class="main-content">
								<div class="product-categories-grid">
									<div class="product-categories-grid-wrap clearfix">
										<div class="product-category-wall wall-row">
											{% for category in categories %}
											<div class="wall-col col-sm-3 title-out height-auto product-category-wall">
												<a href="/product_group/{{ category.slug }}">
													<div class="product-category-grid-item">
														<div class="product-category-grid-item-wrap">
															<div class="product-category-grid-featured-wrap">
																<div class="product-category-grid-featured">
																<img src="{{ MEDIA_URL }}{{ category.image.url }}" alt="IMG-PRODUCT">
																</div>
															</div>
														</div>
													</div>
												</a>
											</div>
											{% endfor %}
										</div>
										<br>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        </article>
    </div>
</div>
{% endblock %}