src/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^ru/$', views.CartDetailRu, name='CartDetailRu'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^add_discount/(?P<phone_number>\d+)/$', views.CartAddDiscount, name='CartAddDiscount'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include, url

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('boss/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    re_path(r'', include(('pasta_family.urls', 'pasta_family'), namespace='pasta_family')),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('orders.urls', 'orders'), namespace='orders')),
    path('novaposhta/', include('novaposhta.urls')),
    url(r'', include(('loyalty_program.urls', 'loyalty_program'), namespace='loyalty_program')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/novaposhta/urls.py
from django.conf.urls import url

from novaposhta import views


app_name = 'novaposhta'


urlpatterns = [

    url('autocomplete', views.autocomplete, name='autocomplete'),

    url('refresh', views.refresh, name='refresh')

]

src/cart/models.py
from django.db import models

# Create your models here.

src/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

src/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from pasta_family.models import Product
from .cart import Cart
from datetime import timedelta
from django.utils import timezone
from .forms import CartAddProductForm
from django.http import HttpResponseRedirect
from loyalty_program.models import Clients, Discounts


def check_date(client_id):
    client = Clients.objects.get(id=client_id)
    prev = timezone.now() - timedelta(days=30)
    if client.discount.percent == 10 and client.last_order_date < prev:
        client.discount_id = Discounts.objects.get(percent=5).id
        client.save()
    return client.discount.percent


@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def CartAddDiscount(request, phone_number):
    cart = Cart(request)
    if Clients.objects.filter(phone_number=phone_number).exists():
        client = Clients.objects.get(phone_number=phone_number)
        percent = check_date(client.id)
        if percent == 10:
            cart.add_discount(discount=percent, orders=client.number_of_orders_10, client_id=client.id)
        else:
            cart.add_discount(discount=percent, client_id=client.id)
    else:
        cart.add_discount(discount=0)


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart/cart.html', {'cart': cart, 'discount': request.session.get("coupon", "None")})


def CartDetailRu(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart/cart_ru.html', {'cart': cart, 'discount': request.session.get("coupon", "None")})

src/cart/templates/cart/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-param" content="_csrf-frontend">
    <meta name="csrf-token" content="lZIw_qwtqs6BMVMFq4bOnXI5fVShSSWHOD7Rc8tV6y7zv3-b_mb6rbYHP1_R_PnaHlwQGPt_YuEAC5wLgyKaQg==">
    <title>Корзина</title>
    <link rel="shortcut icon" href="{% static '/assets/img/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <meta name="description" content="Арахисовая паста для детей и взрослых в Киеве и Украине. Большой ассортимент: арахисовая паста, масло и арахис можете приобрести уже сегодня по выгодной цене!">
    <meta name="keywords" content="">
    <link href="{% static '/assets/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/site.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/template.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/page/page.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/assets/font/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/animate.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/style.css' %}">


    <link id="mainStyles" rel="stylesheet" media="screen" href="{% static '/cart/css/styles.min.css' %}">
    <link id="stylesheet" rel="stylesheet" media="screen" href="{% static '/cart/css/vendor.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/assets/vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/assets/vendor/slick/slick.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/assets/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/assets/css/main.css' %}">
<style>
    select {
        text-align-last: center;
    }
</style>
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '3652317688132524');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=3652317688132524&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->
</head>
<body onload="CheckDiscount()">
<div>
    {% block navbar %}
    {% include 'core/navbar.html' %}
    {% endblock %}
        <div id="content" class="container">
        <div class="row">
            <div class="wpb_wrapper">
                <br><br>
                <h1>Корзина</h1>
                <br>
                <div class="line"></div>
            </div>
            {% with total_items=cart|length %}
            {% if cart|length > 0 %}
            <div class="container p-t-35 p-b-80">
                {% for item in cart %}
                {% with product=item.product %}
                <div class="col-sm-12 col-md-6 col-lg-3 p-b-50">
                    <div class="block2">
                        <div class="block2-img wrap-pic-w of-hidden pos-relative">
                            <a href="/product_group/{{ product.product_group.slug }}/{{ product.slug }}/"><img src="{{ MEDIA_URL }}{{ product.image_main.url }}" alt="IMG-PRODUCT">
                            </a>
                            <a href="/product_group/{{ product.product_group.slug }}/{{ product.slug }}/" class="block2-btn-addwishlist hov-pointer trans-0-4">
                                <i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
                                <i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
                            </a>
                        </div>
                        <div class="block2-txt p-t-20">
                            <a href="/product_group/{{ product.product_group.slug }}/{{ product.slug }}/" class="block2-name dis-block s-text3 p-b-5">
                                {{ product.product_group.name_ua }} {{ product.name_ua }}
                            </a>
                            <a class="block2-name dis-block m-text16 p-b-5">{{ item.total_price }} грн.</a>
                            <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                {% csrf_token %}
                                <div class="flex-m flex-w" style="justify-content: center">
                                    <a class="btn-addcart-product-detail trans-0-4 m-t-10 m-b-10" style="width: 50%; height: 45px">
                                        <input class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" type="submit" value="Оновити">
                                    </a>
                                    <a class="btn-addcart-product-detail trans-0-4 m-t-10 m-b-10 bg0 flex-c-m sizefull bo-rad-23 hov1 s-text1 trans-0-4" style="width: 50%; height: 45px" href="{% url "cart:CartRemove" product.id %}" data-toggle="tooltip" title="Remove item"><i class="icon-cross"></i></a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                {% endwith %}
                {% endfor %}
                <div class="shopping-cart-footer">
                    <div class="column text-lg"><span id="discount" style="display: none;">Сума з урахуванням вашої постійної знижки:</span>Всього: <span class="text-medium">{{ cart.get_total_price_after_discount|floatformat:"0" }} грн.</span></div>
                </div>
                <div class="shopping-cart-footer">
                    <div class="column">
                        <font size="2px">* Замовлення оформлені до 16:00(у робочі дні) відправляються в той же день, після 16:00 - на наступний.</font>
                        <button type="button" class="btn btn-primary" onclick="location.href='/product_group/'">Назад у магазин</button>
                        <button type="button" class="btn btn-success" onclick="location.href='/order/addpaymentinfo'">Оформити покупку</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <br><br>
    <h1>Корзина пуста</h1>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>
</div>
    {% endif %}
    {% endwith %}
    {% block footer %}
    {% include 'core/footer.html' %}
    {% endblock %}
    <script type="text/javascript">
        function CheckDiscount(){
    var discount = "{{ discount }}";
    if (discount==5){
        document.getElementById('discount').style.display = "block";
    } else if (discount==10){
        document.getElementById('discount').style.display = "block";
    }
};
    </script>
    <script src="{% static '/assets/js/jquery-1.11.1.min.js' %}"></script>
        <script src="{% static '/assets/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static '/assets/js/jquery.backstretch.min.js' %}"></script>
        <script src="{% static '/assets/js/wow.min.js' %}"></script>
        <script src="{% static '/assets/js/scripts.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<script type="text/javascript" src="{% static '/assets/vendor/animsition/js/animsition.min.js' %}"></script>
	<script src="{% static '/assets/js/main.js' %}"></script>
</body>
</html>

src/cart/templates/cart/cart_ru.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-param" content="_csrf-frontend">
    <meta name="csrf-token" content="lZIw_qwtqs6BMVMFq4bOnXI5fVShSSWHOD7Rc8tV6y7zv3-b_mb6rbYHP1_R_PnaHlwQGPt_YuEAC5wLgyKaQg==">
    <title>Корзина</title>
    <link rel="shortcut icon" href="{% static '/assets/img/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <meta name="description" content="Арахисовая паста для детей и взрослых в Киеве и Украине. Большой ассортимент: арахисовая паста, масло и арахис можете приобрести уже сегодня по выгодной цене!">
    <meta name="keywords" content="">
    <link href="{% static '/assets/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/site.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/template.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/page/page.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/assets/font/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/animate.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/style.css' %}">


    <link id="mainStyles" rel="stylesheet" media="screen" href="{% static '/cart/css/styles.min.css' %}">
    <link id="stylesheet" rel="stylesheet" media="screen" href="{% static '/cart/css/vendor.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/assets/vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/assets/vendor/slick/slick.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/assets/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/assets/css/main.css' %}">
<style>
    select {
        text-align-last: center;
    }
</style>
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '3652317688132524');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=3652317688132524&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->
</head>
<body onload="CheckDiscount()">
<div>
    {% block navbar %}
    {% include 'core/navbar_ru.html' %}
    {% endblock %}
        <div id="content" class="container-fluid">
        <div class="row">
            <div class="wpb_wrapper">
                <br><br>
                <h1>Корзина</h1>
                <br>
                <div class="line"></div>
            </div>
            {% with total_items=cart|length %}
            {% if cart|length > 0 %}
            <div class="container p-t-35 p-b-80">
                {% for item in cart %} 
                {% with product=item.product %}
                <div class="col-sm-12 col-md-6 col-lg-3 p-b-50">
                    <div class="block2">
                        <div class="block2-img wrap-pic-w of-hidden pos-relative">
                            <a href="/ru/product_group/{{ product.product_group.slug }}/{{ product.slug }}/"><img src="{{ MEDIA_URL }}{{ product.image_main.url }}" alt="IMG-PRODUCT">
                            </a>
                            <a href="/ru/product_group/{{ product.product_group.slug }}/{{ product.slug }}/" class="block2-btn-addwishlist hov-pointer trans-0-4">
                                <i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
                                <i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
                            </a>
                        </div>
                        <div class="block2-txt p-t-20">
                            <a href="/ru/product_group/{{ product_group.slug }}/{{ product.slug }}/" class="block2-name dis-block s-text3 p-b-5">
                                {{ product.product_group.name_ru }} {{ product.name_ru }}
                            </a>
                            <a class="block2-name dis-block m-text16 p-b-5">{{ item.total_price }} грн.</a>
                            <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                {% csrf_token %}
                                <div class="flex-m flex-w" style="justify-content: center">
                                    <a class="btn-addcart-product-detail trans-0-4 m-t-10 m-b-10" style="width: 50%; height: 45px">
                                        <input class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" type="submit" value="Обновить">
                                    </a>
                                    <a class="btn-addcart-product-detail trans-0-4 m-t-10 m-b-10 bg0 flex-c-m sizefull bo-rad-23 hov1 s-text1 trans-0-4" style="width: 50%; height: 45px" href="{% url "cart:CartRemove" product.id %}" data-toggle="tooltip" title="Remove item"><i class="icon-cross"></i></a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                {% endwith %}
                {% endfor %}
                <div class="shopping-cart-footer">
                  <div class="column text-lg"><span id="discount" style="display: none;">Сумма с учетом вашей постоянной скидки:</span>Всего: <span class="text-medium">{{ cart.get_total_price_after_discount|floatformat:"0" }} грн.</span></div>
                </div>
                <div class="shopping-cart-footer">
                    <div class="column">
                        <font size="2px">* Заказы оформлены до 16:00(в рабочие дни) отправляются в тот же день, после 16:00 - на следующий.</font>
                        <button type="button" class="btn btn-primary" onclick="location.href='/ru/product_group/'">В магазин</button>
                        <button type="button" class="btn btn-success" onclick="location.href='/order/ru/addpaymentinfo/'">Оформить покупку</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <br><br>
    <h1>Корзина пустая</h1>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>
</div>
    {% endif %}
    {% endwith %}
    {% block footer %}
    {% include 'core/footer_ru.html' %}
    {% endblock %}
<script type="text/javascript">
        function CheckDiscount(){
    var discount = "{{ discount }}";
    if (discount==5){
        document.getElementById('discount').style.display = "block";
    } else if (discount==10){
        document.getElementById('discount').style.display = "block";
    }
};
    </script>
    <script src="{% static '/assets/js/jquery-1.11.1.min.js' %}"></script>
        <script src="{% static '/assets/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static '/assets/js/jquery.backstretch.min.js' %}"></script>
        <script src="{% static '/assets/js/wow.min.js' %}"></script>
        <script src="{% static '/assets/js/scripts.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<script type="text/javascript" src="{% static '/assets/vendor/animsition/js/animsition.min.js' %}"></script>
	<script src="{% static '/assets/js/main.js' %}"></script>
</body>
</html>